server:
  port: 8080

spring:

  profiles:
    include:
      - connection
      - connection-test
      - cache
      - oauth
      - cloud

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB