auth:
  token:
    token-secret: "camper-test"
    auth-token-expiration-time: 1209600000
    find-password-token-expiration-time: 300
  uris:
    authorized-failure-redirect-uri: http://localhost:8080/auth/error
    authorized-redirect-uri:
      - http://localhost:8080/auth/code

spring:
  profiles:
    include:
      - google
      - kakao
      - naver

---
spring:
  profiles: google
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "53399166692-7iilcpo5kermuvhae83tu2t7tdhp3km5.apps.googleusercontent.com"
            client-secret: "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"
            client-name: google
            redirect-uri: "{baseUrl}/auth/social/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
---
spring:
  profiles: facebook
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: facebook
            client-name: facebook
            redirect-uri: "{baseUrl}/auth/social/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - email
              - public_profile
---
spring:
  profiles: kakao
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: kakao
            client-name: kakao
            redirect-uri: "{baseUrl}/auth/social/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
              - profile_image
              # - birthyear # 비즈 앱으로 전환 후 주석 제거
              - birthday
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-info-uri: https://kapi.kakao.com/v2/user/me
            token-uri: https://kauth.kakao.com/oauth/token
            user-name-attribute: id
---
spring:
  profiles: naver
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: naver
            client-name: naver
            redirect-uri: "{baseUrl}/auth/social/callback/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - email
              - name
              - profile_image
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token
            user-name-attribute: response