server:
  port: 8080

spring:

  profiles:
    include:
      - connection
      - connection-test
      - cache
      - oauth
      - cloud

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1MB # 파일이 메모리에 기록되는 임계값 (default: 0)
      max-file-size: 1MB # 파일의 최대 사이즈 (default: 1MB)
      max-request-size: 10MB # 요청의 최대 사이즈 (default: 10MB)
