cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIA4AIUYZ6KOSBHHNZK
      secret-key: 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
    s3:
      bucket: camping-community

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
